---
  ## Instal bootcamp cluster for TRAINER

  # Set the clustername to trainer.mapr.com
  - name: Change MapR Cluster Name to demo.mapr.com
    shell: "head -n 1 /opt/mapr/conf/mapr-clusters.conf | awk '{print $1}'"
    register: clustername

  - shell: "head -n 1 /opt/mapr/conf/mapr-clusters.conf | awk '{print $2}'"
    register: clustersecure

  - shell: "head -n 1 /opt/mapr/conf/mapr-clusters.conf | awk '{print $3}'"
    register: clustercldbnodes

  - debug:
      msg: "Current content of mapr-clusters.conf: {{clustername.stdout}} {{clustersecure.stdout}} {{clustercldbnodes.stdout}}"

  - debug:
      msg: "New content of mapr-clusters.conf: trainer.mapr.com {{clustersecure.stdout}} {{clustercldbnodes.stdout}}"

  - shell: echo trainer.mapr.com {{clustersecure.stdout}} {{clustercldbnodes.stdout}}  > /opt/mapr/conf/mapr-clusters.conf

  ## Configure Gateway to allow table replication to ATTENDEE clusters
  - name: Configure Gateway to allow table replication to ATTENDEE clusters
    hosts: bootcamp-trainer
    shell: echo "{{item}} >> /tmp/test.txt"
    with_items:
    - "{{ groups['bootcamp-attendee'] }}"

#maprcli cluster gateway set -dstcluster demo.mapr.com -gateways "172.16.4.228"
