---
  ## Instal bootcamp cluster for TRAINER

  # Set the clustername to trainer.mapr.com
  - name: Change MapR Cluster Name to trainer.mapr.com
    shell: "cat /opt/mapr/conf/mapr-clusters.conf | awk '{print $1}'"
    register: clustername

  - shell: "cat /opt/mapr/conf/mapr-clusters.conf | awk '{print $2}'"
    register: clustersecure

  - shell: "cat /opt/mapr/conf/mapr-clusters.conf | awk '{print $3}'"
    register: clustercldbnodes

  - debug:
      msg: "Current content of mapr-clusters.conf: {{clustername.stdout}} {{clustersecure.stdout}} {{clustercldbnodes.stdout}}"

  - debug:
      msg: "New content of mapr-clusters.conf: trainer.mapr.com {{clustersecure.stdout}} {{clustercldbnodes.stdout}}"

  - shell: echo trainer.mapr.com {{clustersecure.stdout}} {{clustercldbnodes.stdout}}  > /opt/mapr/conf/mapr-clusters.conf

  # Download the MapR PACC Image Classification Docker container
  - name: Download the mapr-pacc-image-classification container
    docker_image:
      name: mkieboom/mapr-pacc-image-classification
      state: present
      force: yes

  # Download the yolo image classification files and store the on MapR-FS
  - name: Download yolo image classification files
    get_url:
      url: "{{item}}"
      dest: "/tmp/"
      timeout: 900
    with_items:
    - "https://s3-eu-west-1.amazonaws.com/mkieboom/bootcamp/yolo/tiny-yolo-voc.cfg"
    - "https://s3-eu-west-1.amazonaws.com/mkieboom/bootcamp/yolo/tiny-yolo-voc.weights"
    - "https://s3-eu-west-1.amazonaws.com/mkieboom/bootcamp/yolo/yolo.cfg"
    - "https://s3-eu-west-1.amazonaws.com/mkieboom/bootcamp/yolo/yolo.weights"

  # Create yolo volume using maprcli
  - name: Create the yolo folder on MapR-FS
    shell: maprcli volume create -name yolo -path /yolo

  # Upload the files to MapR-FS (using hadoop put as at this point in time /mapr/ might not be available yet)
  - name: Upload the yolo files to MapR-FS
    shell: hadoop fs -put -f {{item}} /yolo/
    with_items:
    - /tmp/tiny-yolo-voc.cfg
    - /tmp/tiny-yolo-voc.weights
    - /tmp/yolo.cfg
    - /tmp/yolo.weights

  # Create zeppelin volume using maprcli
  - name: Create the yolo folder on MapR-FS
    shell: maprcli volume create -name zeppelin -path /zeppelin

  # Create shared-notebooks folder in the zeppelin volume using hadoop fs (as /mapr might not be available yet)
  - name: Create the yolo folder on MapR-FS
    shell: hadoop fs -mkdir /zeppelin/shared-notebooks
