
- import_playbook: cluster-yarn-spark-drill.yml

## Install Streamsets
- name: Install StreamSets
  hosts: thirdparty-streamsets
  roles:
    - thirdparty-streamsets

## Install Docker
- name: Install Docker
  hosts: thirdparty-docker
  roles:
    - thirdparty-docker

## Run configure.sh
- name: Run configure.sh -R for Eco-system component configuration
  hosts: all:!clients
  roles:
    - mapr-configure-components
