## Instal bootcamp cluster for ATTENDEES

## Install MapR with YARN, Spark and Drill
- import_playbook: bootcamp-fundamentals.yml

## Install Bootcamp specific items for the attendees
- name: Install Bootcamp specific items for the attendees
  hosts: bootcamp-user
  roles:
    #- mapr-kafka-rest        # only required on bootcamp TRAINER cluster
    #- mapr-httpfs            # only required on bootcamp TRAINER cluster
    - mapr-collectd
    - mapr-opentsdb
    - mapr-configure-monitoring-opentsdb
    - bootcamp-attendee

## Configure warden and drill for limited memory consumption
- name: Configure warden and drill for limited memory consumption and restart warden
  hosts: all:!clients
  roles:
    - mapr-configure-memory-medium
    - mapr-configure-components
    - mapr-configure-warden-restart
