---
  ## Instal bootcamp cluster for ATTENDEES

  # Configure the trainer.mapr.com cluster in mapr-clusters.conf to allow data replication
  - name: Add trainer.mapr.com to mapr-clusters.conf to allow data replication
    lineinfile: path=/opt/mapr/conf/mapr-clusters.conf line='{{item}} secure=false {{hostvars[item].ansible_host}}:7222' state=present
    with_inventory_hostnames:
      - bootcamp-trainer-nodes
