---
  ## Instal bootcamp cluster for ATTENDEES

  # Configure the trainer.mapr.com cluster in mapr-clusters.conf to allow data replication
  - name: Add trainer.mapr.com to mapr-clusters.conf to allow data replication
    lineinfile: path=/opt/mapr/conf/mapr-clusters.conf line='{{item}} secure=false {{hostvars[item].ansible_host}}:7222' state=present
    with_inventory_hostnames:
      - bootcamp-trainer-nodes

  # Use a cron job to setup table replication
  - name: Use a cron job to setup table replication
    cron:
      name: "Setup table replication"
      minute: "0"
      job: "/bin/bash /bootcamp/mapr-ansible-playbooks/bootcamp-dataset/scripts/setup_table_replication.sh"

  # Create a record in the 'recent table' list
  - name: Create a record in the 'recent table' list
    shell: echo "/image-classification/output/database/image-output-table" | hadoop fs -put - /user/mapr/.recent_tables
