---
# Configure unsecure cluster
- name: Check if mapr-clusters.conf already exists, if not run configure.sh prior to run disksetup
  stat: path=/opt/mapr/conf/mapr-clusters.conf
  register: p
- name: Run Configure.sh
  shell: /opt/mapr/server/configure.sh -N {{ inventory_hostname }} -Z {{ansible_hostname}} -C {{ansible_hostname}}
  # shell: /opt/mapr/server/configure.sh -N {{ cluster_name }} -Z {{ zookeeper_string }} -C {{ cldb_string }} -u {{ mapr_user }} -g {{mapr_group}} -unsecure -RM {{ resourcemanager_string }} -HS {{ historyserver_string }}
  when: not p.stat.exists

- name: Write disk tmp file
  shell: echo {{ disks }} | tr , '\n' > /tmp/disks.txt
- name: Disk setup
  command: /opt/mapr/server/disksetup -F /tmp/disks.txt
  ignore_errors: True # TODO error result should be handeled

- name: Configure.sh
  shell: /opt/mapr/server/configure.sh -N {{ inventory_hostname }} -Z {{ansible_hostname}} -C {{ansible_hostname}}
